In [3]:
import numpy as np

In [4]:
import pandas as pd

In [5]:
df1 = pd.read_csv("raw_data.csv")
df1.head()

,iso_code,location,date,total_cases,total_deaths,stringency_index,population,gdp_per_capita,human_development_index,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,AFG,Afghanistan,2019-12-31,0.0,0.0,0.0,38928341,1803.987,0.498,#NUM!,#NUM!,#NUM!,17.477233,7.497754494
1,AFG,Afghanistan,2020-01-01,0.0,0.0,0.0,38928341,1803.987,0.498,#NUM!,#NUM!,#NUM!,17.477233,7.497754494
2,AFG,Afghanistan,2020-01-02,0.0,0.0,0.0,38928341,1803.987,0.498,#NUM!,#NUM!,#NUM!,17.477233,7.497754494
3,AFG,Afghanistan,2020-01-03,0.0,0.0,0.0,38928341,1803.987,0.498,#NUM!,#NUM!,#NUM!,17.477233,7.497754494
4,AFG,Afghanistan,2020-01-04,0.0,0.0,0.0,38928341,1803.987,0.498,#NUM!,#NUM!,#NUM!,17.477233,7.497754494

In [6]:
df2 = pd.read_csv("transformed_data.csv")
df2.head()

  CODE      COUNTRY        DATE    HDI   TC   TD  STI        POP    GDPCAP
0  AFG  Afghanistan  2019-12-31  0.498  0.0  0.0  0.0  17.477233  7.497754
1  AFG  Afghanistan  2020-01-01  0.498  0.0  0.0  0.0  17.477233  7.497754
2  AFG  Afghanistan  2020-01-02  0.498  0.0  0.0  0.0  17.477233  7.497754
3  AFG  Afghanistan  2020-01-03  0.498  0.0  0.0  0.0  17.477233  7.497754
4  AFG  Afghanistan  2020-01-04  0.498  0.0  0.0  0.0  17.477233  7.497754

In [7]:
df2.rename({'CODE': 'iso_code','COUNTRY':'location','DATE':'date'}, axis=1)

,iso_code,location,date,HDI,TC,TD,STI,POP,GDPCAP
0,AFG,Afghanistan,2019-12-31,0.498,0.000000,0.000000,0.000000,17.477233,7.497754
1,AFG,Afghanistan,2020-01-01,0.498,0.000000,0.000000,0.000000,17.477233,7.497754
2,AFG,Afghanistan,2020-01-02,0.498,0.000000,0.000000,0.000000,17.477233,7.497754
3,AFG,Afghanistan,2020-01-03,0.498,0.000000,0.000000,0.000000,17.477233,7.497754
4,AFG,Afghanistan,2020-01-04,0.498,0.000000,0.000000,0.000000,17.477233,7.497754
...,...,...,...,...,...,...,...,...,...
50413,ZWE,Zimbabwe,2020-10-15,0.535,8.994048,5.442418,4.341855,16.514381,7.549491
50414,ZWE,Zimbabwe,2020-10-16,0.535,8.996528,5.442418,4.341855,16.514381,7.549491
50415,ZWE,Zimbabwe,2020-10-17,0.535,8.999496,5.442418,4.341855,16.514381,7.549491
50416,ZWE,Zimbabwe,2020-10-18,0.535,9.000853,5.442418,4.341855,16.514381,7.549491
50417,ZWE,Zimbabwe,2020-10-19,0.535,9.005405,5.442418,4.341855,16.514381,7.549491

In [8]:
df3=df2.rename({'CODE': 'iso_code','COUNTRY':'location','DATE':'date'}, axis=1)

In [9]:
pd.merge(df1,df3,how='left',on='iso_code')

,iso_code,location_x,date_x,total_cases,total_deaths,stringency_index,population,gdp_per_capita,human_development_index,Unnamed: 9,...,Unnamed: 12,Unnamed: 13,location_y,date_y,HDI,TC,TD,STI,POP,GDPCAP
0,AFG,Afghanistan,2019-12-31,0.0,0.0,0.00,38928341,1803.987,0.498,#NUM!,...,17.477233,7.497754494,Afghanistan,2019-12-31,0.498,0.000000,0.000000,0.000000,17.477233,7.497754
1,AFG,Afghanistan,2019-12-31,0.0,0.0,0.00,38928341,1803.987,0.498,#NUM!,...,17.477233,7.497754494,Afghanistan,2020-01-01,0.498,0.000000,0.000000,0.000000,17.477233,7.497754
2,AFG,Afghanistan,2019-12-31,0.0,0.0,0.00,38928341,1803.987,0.498,#NUM!,...,17.477233,7.497754494,Afghanistan,2020-01-02,0.498,0.000000,0.000000,0.000000,17.477233,7.497754
3,AFG,Afghanistan,2019-12-31,0.0,0.0,0.00,38928341,1803.987,0.498,#NUM!,...,17.477233,7.497754494,Afghanistan,2020-01-03,0.498,0.000000,0.000000,0.000000,17.477233,7.497754
4,AFG,Afghanistan,2019-12-31,0.0,0.0,0.00,38928341,1803.987,0.498,#NUM!,...,17.477233,7.497754494,Afghanistan,2020-01-04,0.498,0.000000,0.000000,0.000000,17.477233,7.497754
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12481889,ZWE,Zimbabwe,2020-10-19,8147.0,231.0,76.85,14862927,1899.775,0.535,9.00540504,...,16.514381,7.549490737,Zimbabwe,2020-10-15,0.535,8.994048,5.442418,4.341855,16.514381,7.549491
12481890,ZWE,Zimbabwe,2020-10-19,8147.0,231.0,76.85,14862927,1899.775,0.535,9.00540504,...,16.514381,7.549490737,Zimbabwe,2020-10-16,0.535,8.996528,5.442418,4.341855,16.514381,7.549491
12481891,ZWE,Zimbabwe,2020-10-19,8147.0,231.0,76.85,14862927,1899.775,0.535,9.00540504,...,16.514381,7.549490737,Zimbabwe,2020-10-17,0.535,8.999496,5.442418,4.341855,16.514381,7.549491
12481892,ZWE,Zimbabwe,2020-10-19,8147.0,231.0,76.85,14862927,1899.775,0.535,9.00540504,...,16.514381,7.549490737,Zimbabwe,2020-10-18,0.535,9.000853,5.442418,4.341855,16.514381,7.549491
12481893,ZWE,Zimbabwe,2020-10-19,8147.0,231.0,76.85,14862927,1899.775,0.535,9.00540504,...,16.514381,7.549490737,Zimbabwe,2020-10-19,0.535,9.005405,5.442418,4.341855,16.514381,7.549491

In [10]:
df4=pd.merge(df1,df3,how='left',on='iso_code')

In [16]:
df4

,iso_code,location_x,date_x,total_cases,total_deaths,stringency_index,population,gdp_per_capita,human_development_index,Unnamed: 9,...,Unnamed: 12,Unnamed: 13,location_y,date_y,HDI,TC,TD,STI,POP,GDPCAP
0,AFG,Afghanistan,2019-12-31,0.0,0.0,0.00,38928341,1803.987,0.498,#NUM!,...,17.477233,7.497754494,Afghanistan,2019-12-31,0.498,0.000000,0.000000,0.000000,17.477233,7.497754
1,AFG,Afghanistan,2019-12-31,0.0,0.0,0.00,38928341,1803.987,0.498,#NUM!,...,17.477233,7.497754494,Afghanistan,2020-01-01,0.498,0.000000,0.000000,0.000000,17.477233,7.497754
2,AFG,Afghanistan,2019-12-31,0.0,0.0,0.00,38928341,1803.987,0.498,#NUM!,...,17.477233,7.497754494,Afghanistan,2020-01-02,0.498,0.000000,0.000000,0.000000,17.477233,7.497754
3,AFG,Afghanistan,2019-12-31,0.0,0.0,0.00,38928341,1803.987,0.498,#NUM!,...,17.477233,7.497754494,Afghanistan,2020-01-03,0.498,0.000000,0.000000,0.000000,17.477233,7.497754
4,AFG,Afghanistan,2019-12-31,0.0,0.0,0.00,38928341,1803.987,0.498,#NUM!,...,17.477233,7.497754494,Afghanistan,2020-01-04,0.498,0.000000,0.000000,0.000000,17.477233,7.497754
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12481889,ZWE,Zimbabwe,2020-10-19,8147.0,231.0,76.85,14862927,1899.775,0.535,9.00540504,...,16.514381,7.549490737,Zimbabwe,2020-10-15,0.535,8.994048,5.442418,4.341855,16.514381,7.549491
12481890,ZWE,Zimbabwe,2020-10-19,8147.0,231.0,76.85,14862927,1899.775,0.535,9.00540504,...,16.514381,7.549490737,Zimbabwe,2020-10-16,0.535,8.996528,5.442418,4.341855,16.514381,7.549491
12481891,ZWE,Zimbabwe,2020-10-19,8147.0,231.0,76.85,14862927,1899.775,0.535,9.00540504,...,16.514381,7.549490737,Zimbabwe,2020-10-17,0.535,8.999496,5.442418,4.341855,16.514381,7.549491
12481892,ZWE,Zimbabwe,2020-10-19,8147.0,231.0,76.85,14862927,1899.775,0.535,9.00540504,...,16.514381,7.549490737,Zimbabwe,2020-10-18,0.535,9.000853,5.442418,4.341855,16.514381,7.549491
12481893,ZWE,Zimbabwe,2020-10-19,8147.0,231.0,76.85,14862927,1899.775,0.535,9.00540504,...,16.514381,7.549490737,Zimbabwe,2020-10-19,0.535,9.005405,5.442418,4.341855,16.514381,7.549491

In [17]:
# Top 10 Countries with Highest Covid Cases

df5=df4.groupby('location_x').max().sort_values(by='total_cases',ascending=False)[:10]
df5

,iso_code,date_x,total_cases,total_deaths,stringency_index,population,gdp_per_capita,human_development_index,Unnamed: 9,Unnamed: 10,...,Unnamed: 12,Unnamed: 13,location_y,date_y,HDI,TC,TD,STI,POP,GDPCAP
location_x,,,,,,,,,,,,,,,,,,,,,
United States,USA,2020-10-19,8154595.0,219674.0,72.69,331002647,54225.446,0.924,9.884508586,9.933434629,...,19.617637,10.90090556,United States,2020-10-19,0.924,15.914092,12.299900,4.286204,19.617637,10.900906
India,IND,2020-10-19,7550273.0,114610.0,100.00,1380004385,6426.674,0.640,9.970819045,9.980633762,...,21.045353,8.768212421,India,2020-10-19,0.640,15.837094,11.649290,4.605170,21.045353,8.768212
Brazil,BRA,2020-10-19,5235344.0,153905.0,81.02,212559409,14103.452,0.759,9.939192477,9.999388467,...,19.174732,9.554174869,Brazil,2020-10-19,0.759,15.470943,11.944091,4.394696,19.174732,9.554175
Russia,RUS,2020-10-19,1399334.0,24187.0,87.04,145934460,24765.954,0.816,9.957123102,9.992642464,...,18.798668,10.11722517,Russia,2020-10-19,0.816,14.151507,10.093571,4.466368,18.798668,10.117225
Argentina,ARG,2020-10-19,989667.0,26267.0,100.00,45195777,18933.907,0.825,9.999115864,9.990903015,...,17.626514,9.848709615,Argentina,2020-10-19,0.825,13.805124,10.176069,4.605170,17.626514,9.848710
Colombia,COL,2020-10-19,959572.0,28970.0,90.74,50882884,13254.949,0.747,9.997933723,9.990444761,...,17.745037,9.492126271,Colombia,2020-10-19,0.747,13.774243,10.274016,4.507998,17.745037,9.492126
Spain,ESP,2020-10-18,936560.0,33775.0,85.19,46754783,34272.360,0.891,9.986679143,9.985850643,...,17.660427,10.44209448,Spain,2020-10-18,0.891,13.749969,10.427476,4.444884,17.660427,10.442094
France,FRA,2020-10-19,897034.0,33477.0,87.96,65273512,38605.671,0.901,9.896261507,9.992230762,...,17.994097,10.56115446,France,2020-10-19,0.901,13.706849,10.418614,4.476882,17.994097,10.561154
Peru,PER,2020-10-19,868675.0,33759.0,96.30,32971846,12236.706,0.750,9.98266835,9.985666438,...,17.311165,9.412195402,Peru,2020-10-19,0.750,13.674724,10.427002,4.567468,17.311165,9.412195
Mexico,MEX,2020-10-19,851227.0,86167.0,82.41,128932753,17336.469,0.774,9.993008278,9.990811381,...,18.674802,9.760567596,Mexico,2020-10-19,0.774,13.654434,11.364043,4.411707,18.674802,9.760568

In [18]:
#Total number of deaths among the countries with the highest number of covid-19 cases

df6=df5['total_deaths'].sum(axis=0)
df6

754791.0

In [19]:
#Percentage of total deaths and total cases among all the countries with the highest number of covid-19 cases
df7=df5['total_deaths'] / df5['total_cases']*100
df7

location_x
United States     2.693868
India             1.517958
Brazil            2.939730
Russia            1.728465
Argentina         2.654125
Colombia          3.019054
Spain             3.606283
France            3.731966
Peru              3.886264
Mexico           10.122682
dtype: float64

In [20]:
#calculate the death rate of Covid-19 cases
df8=df4['total_deaths'].sum(axis=0)
df8

33407053441.0

In [21]:
df9=df4['total_cases'].sum(axis=0)
df9

884130454733.0

In [22]:
df10=df8/df9*100
df10

3.778520835037704

In [23]:
#stringency index-: It is a composite measure of response indicators, including school closures, workplace closures, 
#and travel bans. It shows how strictly countries are following these measures to control the spread of covid-19

df11=df4['stringency_index'].mean()
df11

55.26386179041962

#  analyze the impacts of covid-19 on the economy

In [40]:
#GDP per capita is the primary factor for analyzing the economic slowdowns caused due to the outbreak of covdf4.dtypes
df4.dtypes

iso_code                    object
location_x                  object
date_x                      object
total_cases                float64
total_deaths               float64
stringency_index           float64
population                   int64
gdp_per_capita             float64
human_development_index    float64
Unnamed: 9                  object
Unnamed: 10                 object
Unnamed: 11                 object
Unnamed: 12                float64
Unnamed: 13                 object
location_y                  object
date_y                      object
HDI                        float64
TC                         float64
TD                         float64
STI                        float64
POP                        float64
GDPCAP                     float64
dtype: object

In [45]:
df4["date_x"] = pd.to_datetime(df4["date_x"])

In [46]:
df4.dtypes

iso_code                           object
location_x                         object
date_x                     datetime64[ns]
total_cases                       float64
total_deaths                      float64
stringency_index                  float64
population                          int64
gdp_per_capita                    float64
human_development_index           float64
Unnamed: 9                         object
Unnamed: 10                        object
Unnamed: 11                        object
Unnamed: 12                       float64
Unnamed: 13                        object
location_y                         object
date_y                             object
HDI                               float64
TC                                float64
TD                                float64
STI                               float64
POP                               float64
GDPCAP                            float64
dtype: object

In [47]:
df12=df4

In [48]:
df12

,iso_code,location_x,date_x,total_cases,total_deaths,stringency_index,population,gdp_per_capita,human_development_index,Unnamed: 9,...,Unnamed: 12,Unnamed: 13,location_y,date_y,HDI,TC,TD,STI,POP,GDPCAP
0,AFG,Afghanistan,2019-12-31,0.0,0.0,0.00,38928341,1803.987,0.498,#NUM!,...,17.477233,7.497754494,Afghanistan,2019-12-31,0.498,0.000000,0.000000,0.000000,17.477233,7.497754
1,AFG,Afghanistan,2019-12-31,0.0,0.0,0.00,38928341,1803.987,0.498,#NUM!,...,17.477233,7.497754494,Afghanistan,2020-01-01,0.498,0.000000,0.000000,0.000000,17.477233,7.497754
2,AFG,Afghanistan,2019-12-31,0.0,0.0,0.00,38928341,1803.987,0.498,#NUM!,...,17.477233,7.497754494,Afghanistan,2020-01-02,0.498,0.000000,0.000000,0.000000,17.477233,7.497754
3,AFG,Afghanistan,2019-12-31,0.0,0.0,0.00,38928341,1803.987,0.498,#NUM!,...,17.477233,7.497754494,Afghanistan,2020-01-03,0.498,0.000000,0.000000,0.000000,17.477233,7.497754
4,AFG,Afghanistan,2019-12-31,0.0,0.0,0.00,38928341,1803.987,0.498,#NUM!,...,17.477233,7.497754494,Afghanistan,2020-01-04,0.498,0.000000,0.000000,0.000000,17.477233,7.497754
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12481889,ZWE,Zimbabwe,2020-10-19,8147.0,231.0,76.85,14862927,1899.775,0.535,9.00540504,...,16.514381,7.549490737,Zimbabwe,2020-10-15,0.535,8.994048,5.442418,4.341855,16.514381,7.549491
12481890,ZWE,Zimbabwe,2020-10-19,8147.0,231.0,76.85,14862927,1899.775,0.535,9.00540504,...,16.514381,7.549490737,Zimbabwe,2020-10-16,0.535,8.996528,5.442418,4.341855,16.514381,7.549491
12481891,ZWE,Zimbabwe,2020-10-19,8147.0,231.0,76.85,14862927,1899.775,0.535,9.00540504,...,16.514381,7.549490737,Zimbabwe,2020-10-17,0.535,8.999496,5.442418,4.341855,16.514381,7.549491
12481892,ZWE,Zimbabwe,2020-10-19,8147.0,231.0,76.85,14862927,1899.775,0.535,9.00540504,...,16.514381,7.549490737,Zimbabwe,2020-10-18,0.535,9.000853,5.442418,4.341855,16.514381,7.549491
12481893,ZWE,Zimbabwe,2020-10-19,8147.0,231.0,76.85,14862927,1899.775,0.535,9.00540504,...,16.514381,7.549490737,Zimbabwe,2020-10-19,0.535,9.005405,5.442418,4.341855,16.514381,7.549491

In [49]:
df12.dtypes

iso_code                           object
location_x                         object
date_x                     datetime64[ns]
total_cases                       float64
total_deaths                      float64
stringency_index                  float64
population                          int64
gdp_per_capita                    float64
human_development_index           float64
Unnamed: 9                         object
Unnamed: 10                        object
Unnamed: 11                        object
Unnamed: 12                       float64
Unnamed: 13                        object
location_y                         object
date_y                             object
HDI                               float64
TC                                float64
TD                                float64
STI                               float64
POP                               float64
GDPCAP                            float64
dtype: object

In [50]:
df12['year']=df12['date_x'].dt.year

In [51]:
df12

,iso_code,location_x,date_x,total_cases,total_deaths,stringency_index,population,gdp_per_capita,human_development_index,Unnamed: 9,...,Unnamed: 13,location_y,date_y,HDI,TC,TD,STI,POP,GDPCAP,year
0,AFG,Afghanistan,2019-12-31,0.0,0.0,0.00,38928341,1803.987,0.498,#NUM!,...,7.497754494,Afghanistan,2019-12-31,0.498,0.000000,0.000000,0.000000,17.477233,7.497754,2019
1,AFG,Afghanistan,2019-12-31,0.0,0.0,0.00,38928341,1803.987,0.498,#NUM!,...,7.497754494,Afghanistan,2020-01-01,0.498,0.000000,0.000000,0.000000,17.477233,7.497754,2019
2,AFG,Afghanistan,2019-12-31,0.0,0.0,0.00,38928341,1803.987,0.498,#NUM!,...,7.497754494,Afghanistan,2020-01-02,0.498,0.000000,0.000000,0.000000,17.477233,7.497754,2019
3,AFG,Afghanistan,2019-12-31,0.0,0.0,0.00,38928341,1803.987,0.498,#NUM!,...,7.497754494,Afghanistan,2020-01-03,0.498,0.000000,0.000000,0.000000,17.477233,7.497754,2019
4,AFG,Afghanistan,2019-12-31,0.0,0.0,0.00,38928341,1803.987,0.498,#NUM!,...,7.497754494,Afghanistan,2020-01-04,0.498,0.000000,0.000000,0.000000,17.477233,7.497754,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12481889,ZWE,Zimbabwe,2020-10-19,8147.0,231.0,76.85,14862927,1899.775,0.535,9.00540504,...,7.549490737,Zimbabwe,2020-10-15,0.535,8.994048,5.442418,4.341855,16.514381,7.549491,2020
12481890,ZWE,Zimbabwe,2020-10-19,8147.0,231.0,76.85,14862927,1899.775,0.535,9.00540504,...,7.549490737,Zimbabwe,2020-10-16,0.535,8.996528,5.442418,4.341855,16.514381,7.549491,2020
12481891,ZWE,Zimbabwe,2020-10-19,8147.0,231.0,76.85,14862927,1899.775,0.535,9.00540504,...,7.549490737,Zimbabwe,2020-10-17,0.535,8.999496,5.442418,4.341855,16.514381,7.549491,2020
12481892,ZWE,Zimbabwe,2020-10-19,8147.0,231.0,76.85,14862927,1899.775,0.535,9.00540504,...,7.549490737,Zimbabwe,2020-10-18,0.535,9.000853,5.442418,4.341855,16.514381,7.549491,2020
12481893,ZWE,Zimbabwe,2020-10-19,8147.0,231.0,76.85,14862927,1899.775,0.535,9.00540504,...,7.549490737,Zimbabwe,2020-10-19,0.535,9.005405,5.442418,4.341855,16.514381,7.549491,2020

In [55]:
df13=df12[(df12['year']==2019)]
df13

,iso_code,location_x,date_x,total_cases,total_deaths,stringency_index,population,gdp_per_capita,human_development_index,Unnamed: 9,...,Unnamed: 13,location_y,date_y,HDI,TC,TD,STI,POP,GDPCAP,year
0,AFG,Afghanistan,2019-12-31,0.0,0.0,0.0,38928341,1803.987,0.498,#NUM!,...,7.497754494,Afghanistan,2019-12-31,0.498,0.000000,0.000000,0.000000,17.477233,7.497754,2019
1,AFG,Afghanistan,2019-12-31,0.0,0.0,0.0,38928341,1803.987,0.498,#NUM!,...,7.497754494,Afghanistan,2020-01-01,0.498,0.000000,0.000000,0.000000,17.477233,7.497754,2019
2,AFG,Afghanistan,2019-12-31,0.0,0.0,0.0,38928341,1803.987,0.498,#NUM!,...,7.497754494,Afghanistan,2020-01-02,0.498,0.000000,0.000000,0.000000,17.477233,7.497754,2019
3,AFG,Afghanistan,2019-12-31,0.0,0.0,0.0,38928341,1803.987,0.498,#NUM!,...,7.497754494,Afghanistan,2020-01-03,0.498,0.000000,0.000000,0.000000,17.477233,7.497754,2019
4,AFG,Afghanistan,2019-12-31,0.0,0.0,0.0,38928341,1803.987,0.498,#NUM!,...,7.497754494,Afghanistan,2020-01-04,0.498,0.000000,0.000000,0.000000,17.477233,7.497754,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12266904,VNM,Vietnam,2019-12-31,NaN,NaN,NaN,97338583,6171.884,0.694,#NUM!,...,8.727759419,Vietnam,2020-10-15,0.694,7.022868,3.555348,3.948355,18.393706,8.727759,2019
12266905,VNM,Vietnam,2019-12-31,NaN,NaN,NaN,97338583,6171.884,0.694,#NUM!,...,8.727759419,Vietnam,2020-10-16,0.694,7.024649,3.555348,3.948355,18.393706,8.727759,2019
12266906,VNM,Vietnam,2019-12-31,NaN,NaN,NaN,97338583,6171.884,0.694,#NUM!,...,8.727759419,Vietnam,2020-10-17,0.694,7.024649,3.555348,3.948355,18.393706,8.727759,2019
12266907,VNM,Vietnam,2019-12-31,NaN,NaN,NaN,97338583,6171.884,0.694,#NUM!,...,8.727759419,Vietnam,2020-10-18,0.694,7.026427,3.555348,3.948355,18.393706,8.727759,2019
12266908,VNM,Vietnam,2019-12-31,NaN,NaN,NaN,97338583,6171.884,0.694,#NUM!,...,8.727759419,Vietnam,2020-10-19,0.694,7.033506,3.555348,3.948355,18.393706,8.727759,2019

In [56]:
df14=df13['gdp_per_capita'].mean()
df14

32107.97299048318

In [62]:
df15=df12[(df12['year']==2020)]
df15

MemoryError: Unable to allocate 95.1 MiB for an array with shape (12462496, 1) and data type int64

In [11]:
df16=df4['gdp_per_capita'].mean()
df16

22289.997377621123

In [12]:
df17=df4['GDPCAP'].mean()
df17

8.514503569594321

In [13]:
df18=df4['human_development_index'].mean()
df18

0.7335974337375211

In [14]:
df19=df4['HDI'].mean()
df19

0.7335974337375211